#ifndef DELTA_ASDA_ETHERCAT_REGISTRY_IDX_H
#define DELTA_ASDA_ETHERCAT_REGISTRY_IDX_H

// CANopen 301
#define DEVICE_TYPE_IDX                             0x1000
#define ERROR_REGISTER_IDX                          0x1001
#define RX_PDO1_IDX                                 0x1600
#define RX_PDO2_IDX                                 0x1601
#define RX_PDO3_IDX                                 0x1602
#define RX_PDO4_IDX                                 0x1603
#define TX_PDO1_IDX                                 0x1A00
#define TX_PDO2_IDX                                 0x1A01
#define TX_PDO3_IDX                                 0x1A02
#define TX_PDO4_IDX                                 0x1A03
#define SYNC_MANAGER_OUTPUT_PARAMETER_IDX           0x1C32
#define SYNC_MANAGER_INPUT_PARAMETER_IDX            0x1C33
// CiA 402
#define ERROR_CODE_IDX                              0x603F
#define CONTROL_WORD_IDX                            0x6040
#define STATUS_WORD_IDX                             0x6041
#define SHUTDOWN_OPTION_CODE_IDX                    0x605B
#define FAULT_REACTION_OPTION_CODE_IDX              0x605E
#define MODE_OF_OPERATION_IDX                       0x6060
#define MODE_OF_OPERATION_DISPLAY_IDX               0x6061
#define POSITION_DEMAND_VALUE_PUU_IDX               0x6062
#define POSITION_ACTUAL_VALUE_INCREMENT_IDX         0x6063
#define POSITION_ACTUAL_VALUE_IDX                   0x6064
#define FOLLOWING_ERROR_WINDOW_IDX                  0x6065
#define POSITION_WINDOW_IDX                         0x6067
#define POSITION_WINDOW_TIME_IDX                    0x6068
#define VELOCITY_DEMAND_VALUE_IDX                   0x606B
#define VELOCITY_ACTUAL_VALUE_IDX                   0x606C
#define VELOCITY_WINDOW_IDX                         0x606D
#define VELOCITY_WINDOW_TIME_IDX                    0x606E
#define VELOCITY_THRESHOLD_IDX                      0x606F
#define TARGET_TORQUE_IDX                           0x6071
#define MAX_TORQUE_IDX                              0x6072
#define TORQUE_DEMAND_VALUE_IDX                     0x6074
#define MOTOR_RATED_CURRENT_IDX                     0x6075
#define MOTOR_RATED_TORQUE_IDX                      0x6076
#define TORQUE_ACTUAL_VALUE_IDX                     0x6077
#define CURRENT_ACTUAL_VALUE_IDX                    0x6078
#define TARGET_POSITION_IDX                         0x607A
#define HOME_OFFSET_IDX                             0x607C
#define SOFTWARE_POSITION_LIMIT_IDX                 0x607D
#define POLARITY_IDX                                0x607E
#define MAX_PROFILE_SPEED_IDX                       0x607F
#define MAX_MOTOR_SPEED_IDX                         0x6080
#define PROFILE_VELOCITY_IDX                        0x6081
#define PROFILE_ACCELERATION_IDX                    0x6083
#define PROFILE_DECELERATION_IDX                    0x6084
#define QUICKSTOP_DECELERATION_IDX                  0x6085
#define MOTION_PROFILE_TYPE_IDX                     0x6086
#define TORQUE_SLOPE_IDX                            0x6087
#define POSITION_FACTOR_IDX                         0x6093
#define HOMING_METHOD_IDX                           0x6098
#define HOMING_SPEEDS_IDX                           0x6099
#define HOMING_ACCELERATION_IDX                     0x609A
#define POSITION_OFFSET_IDX                         0x60B0
#define VELOCITY_OFFSET_IDX                         0x60B1
#define TORQUE_OFFSET_IDX                           0x60B2
#define TOUCH_PROBE_FUNCTION_IDX                    0x60B8
#define TOUCH_PROBE_STATUS_IDX                      0x60B9
#define TOUCH_PROBE_POSITION_1_POSITIVE_VALUE_IDX   0x60BA
#define TOUCH_PROBE_POSITION_1_NEGATIVE_VALUE_IDX   0x60BB
#define TOUCH_PROBE_POSITION_2_POSITIVE_VALUE_IDX   0x60BC
#define TOUCH_PROBE_POSITION_2_NEGATIVE_VALUE_IDX   0x60BD
#define INTERPOLATION_SUB_MODE_SELECT_IDX           0x60C0
#define INTERPOLATION_DATA_RECORD_IDX               0x60C1
#define INTERPOLATION_TIME_PERIOD_IDX               0x60C2
#define INTERPOLATION_MAX_ACCELERATION_IDX          0x60C5
#define INTERPOLATION_MAX_DECELERATION_IDX          0x60C6
#define POSITIONING_OPTION_CODE_IDX                 0x60F2
#define FOLLOWING_ERROR_ACTUAL_VALUE_IDX            0x60F4
#define POSITION_DEMAND_VALUE_IDX                   0x60FC
#define DIGITAL_INPUTS_IDX                          0x60FD
#define TARGET_VELOCITY_IDX                         0x60FF
#define SUPPORTED_DRIVE_MODES_IDX                   0x6502

#endif
